### PR TITLE
Enhancement | Mobile UX

### PR DESCRIPTION
**Pull request by Arjona99**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=n25hjtz)
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=BgF-nhn)
# Pull Request Template

## Description

Please include a summary of the change and issue(s) fixed. Also, mention relevant motivation, context, and any dependencies that this change requires.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Behtsa — CHANGES_REQUESTED** [review]
I was checking this pr and I find a bug.
Scrolling is being affected, you can not scroll through the conversation, this affects mobile and web, and the white spaces on mobile became more notorious. Also web version seems like it is flashing. 

<details>
<summary>No scroll, affecting mobile and desktop</summary>

https://user-images.githubusercontent.com/9289461/224723087-75a8bbd7-7693-4c42-90e4-a70498e22a53.mov

</details>

 

<details>
<summary>Original behaviour with scroll</summary>

https://user-images.githubusercontent.com/9289461/224723784-ecf54dca-7d29-47bb-8dfa-009f6cb3f01d.mov


</details>


And my second thought is that for the web we are changing the position of the messages also to the bottom, I believe this should be only for mobile. WDYT? 

<details>
<summary>Bootom text in web</summary>

image


</details>

**Comment by Arjona99** [comment]
Thanks for noticing the scrolling issue! I have fixed it 👍🏼  and about your second comment, I decided to preserve that behavior on mobile and desktop because is the way almost every messaging service works (whats, slack, fb messenger, etc) wdyt? @Behtsa

**Comment by Arjona99** [comment]
@Behtsa I also fixed the issue where the input text was always in focus state, know is fixed and only shows the glowing border when is on focus mode 👍🏼

**Review by Behtsa — APPROVED** [review]
LGTM!!! Great job ⭐

**Pull request merged**
